--------------------------------------------------------
--  파일이 생성됨 - 수요일-5월-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MEMBER" 
   (	"ID" VARCHAR2(12 BYTE), 
	"PW" VARCHAR2(12 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MEMBER
SET DEFINE OFF;
Insert into SYSTEM.MEMBER (ID,PW,EMAIL,NAME,TEL) values ('kkt','1234','hty@org.com','hty@org.com','1324-1234-1234');
Insert into SYSTEM.MEMBER (ID,PW,EMAIL,NAME,TEL) values ('kkt1','1234','kim','123@asdf','123');
Insert into SYSTEM.MEMBER (ID,PW,EMAIL,NAME,TEL) values ('admin','1234','hty','htyy@naver.com','23-123-1234');
Insert into SYSTEM.MEMBER (ID,PW,EMAIL,NAME,TEL) values ('jdj','ac89','정도준','jdjac@naver.com','010-7979-1004');
--------------------------------------------------------
--  DDL for Index SYS_C008361
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008361" ON "SYSTEM"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MEMBER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MEMBER" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
